codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "100...100"

  status:
    project:
      default:
        target: auto
        threshold: "0"
#    patch:
#      default:
#        target: auto
#        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
  require_base: yes
  require_head: yes
  branches: null
  flags: no
  paths: no
  yaml: yes
