name: build and test
on: [push, pull_request]
jobs:
  build-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
        working-directory: ./bridge
      - run: npx tsc
        working-directory: ./bridge
      - run: npm run coverage
        working-directory: ./bridge
      - run: bash <(curl -s https://codecov.io/bash)
        name: codecov
        working-directory: ./bridge
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  build-solidity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: contracts
      - run: npm run build
        working-directory: contracts
      - run: npm run lint
        working-directory: contracts
  build-bridge-www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn
        working-directory: ./bridge-www
      - run: |
          cp package.json /tmp/package.json
          jq --arg repository "$REPOSITORY" '.homepage = ($repository | split("/") | "https://\(.[0]).github.io/\(.[1])")' < /tmp/package.json > package.json
          yarn build
        working-directory: ./bridge-www
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bridge-www/build
  build-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python -m pip install mypy
      - run: python -m pip install -r scripts/observer/requirements.txt -r scripts/observer/requirements-dev.txt
      - run: python -m mypy scripts/observer
