on: push
name: push docker image
jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build
        run: docker build -t planetariumhq/9c-ethereum-bridge:git-${{ github.sha }} .
        working-directory: bridge
      - name: push (publish)
        run: docker push planetariumhq/9c-ethereum-bridge:git-${{ github.sha }}
