on: push

name: push docker image
jobs:
  build_and_push:
    uses: planetarium/.github/.github/workflows/push_docker_image.yaml@47d9a17c7c0bacae638b30c203ef7bf1570821cf
    with:
      repository: 9c-ethereum-bridge
      working_directory: bridge
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
