on: push
name: push docker image
jobs:
  build_and_push:
    uses: planetarium/.github/.github/workflows/push_docker_image.yaml@dc763b140dc0a38b6906680a601f8f79026a6f36
    with:
      repository: 9c-ethereum-bridge
